using Azure;
using Azure.AI.Inference;
using Azure.Core;
using Azure.Identity;
using System.Net;

namespace AIKit.Clients.AzureOpenAI;

/// <summary>
/// Internal creator for Azure OpenAI clients with shared configuration logic.
/// </summary>
internal static class ClientCreator
{
    /// <summary>
    /// Creates a ChatCompletionsClient from the provided settings.
    /// </summary>
    /// <param name="endpoint">The Azure OpenAI endpoint.</param>
    /// <param name="apiKey">The API key (optional if using credential).</param>
    /// <param name="useDefaultAzureCredential">Whether to use default Azure credential.</param>
    /// <param name="tokenCredential">Custom token credential.</param>
    /// <param name="httpClient">Optional pre-configured HttpClient.</param>
    /// <param name="proxy">Optional web proxy.</param>
    /// <param name="timeoutSeconds">Timeout in seconds.</param>
    /// <param name="userAgent">Optional user agent.</param>
    /// <param name="customHeaders">Optional custom headers.</param>
    /// <returns>The configured ChatCompletionsClient.</returns>
    internal static ChatCompletionsClient CreateChatCompletionsClient(
        string endpoint,
        string? apiKey = null,
        bool useDefaultAzureCredential = false,
        TokenCredential? tokenCredential = null,
        HttpClient? httpClient = null,
        IWebProxy? proxy = null,
        int timeoutSeconds = 30,
        string? userAgent = null,
        Dictionary<string, string>? customHeaders = null)
    {
        if (httpClient == null)
        {
            var handler = new HttpClientHandler();
            if (proxy != null)
            {
                handler.Proxy = proxy;
            }
            httpClient = new HttpClient(handler) { Timeout = TimeSpan.FromSeconds(timeoutSeconds) };
        }
        else if (proxy != null)
        {
            // Log warning if needed, but since no logger, skip
        }

        if (!string.IsNullOrEmpty(userAgent))
        {
            httpClient.DefaultRequestHeaders.UserAgent.ParseAdd(userAgent);
        }

        if (customHeaders != null)
        {
            foreach (var kvp in customHeaders)
            {
                httpClient.DefaultRequestHeaders.Add(kvp.Key, kvp.Value);
            }
        }

        ChatCompletionsClient client;

        if (tokenCredential != null)
        {
            client = new ChatCompletionsClient(
                new Uri(endpoint),
                tokenCredential);
        }
        else if (useDefaultAzureCredential)
        {
            client = new ChatCompletionsClient(
                new Uri(endpoint),
                new DefaultAzureCredential());
        }
        else
        {
            client = new ChatCompletionsClient(
                new Uri(endpoint),
                new AzureKeyCredential(apiKey!));
        }

        return client;
    }

    /// <summary>
    /// Creates an EmbeddingsClient from the provided settings.
    /// </summary>
    /// <param name="endpoint">The Azure OpenAI endpoint.</param>
    /// <param name="apiKey">The API key (optional if using credential).</param>
    /// <param name="useDefaultAzureCredential">Whether to use default Azure credential.</param>
    /// <param name="tokenCredential">Custom token credential.</param>
    /// <returns>The configured EmbeddingsClient.</returns>
    internal static EmbeddingsClient CreateEmbeddingsClient(
        string endpoint,
        string? apiKey = null,
        bool useDefaultAzureCredential = false,
        TokenCredential? tokenCredential = null)
    {
        EmbeddingsClient client;

        if (tokenCredential != null)
        {
            client = new EmbeddingsClient(
                new Uri(endpoint),
                tokenCredential);
        }
        else if (useDefaultAzureCredential)
        {
            client = new EmbeddingsClient(
                new Uri(endpoint),
                new DefaultAzureCredential());
        }
        else
        {
            client = new EmbeddingsClient(
                new Uri(endpoint),
                new AzureKeyCredential(apiKey!));
        }

        return client;
    }
}

// Generated by Copilot