// Generated by Copilot
using Shouldly;
using Xunit;

namespace AIKit.Storage.Tests;

public class StorageProviderBuilderTests
{
    [Fact]
    public void AzureBlobStorageBuilder_Build_WithValidConfig_ReturnsProvider()
    {
        // Arrange
        var builder = new AIKit.Storage.Azure.StorageProviderBuilder()
            .WithConnectionString("UseDevelopmentStorage=true")
            .WithContainerName("test-container");

        // Act
        var provider = builder.Build();

        // Assert
        provider.ShouldNotBeNull();
        provider.ShouldBeOfType<AIKit.Storage.Azure.AzureBlobStorageProvider>();
    }

    [Fact]
    public void AzureBlobStorageBuilder_Build_WithOptions_ReturnsProviderWithOptions()
    {
        // Arrange
        var options = new AIKit.Storage.Azure.AzureBlobStorageOptions
        {
            AutoCreateContainer = false,
            DefaultSasExpiration = TimeSpan.FromMinutes(30)
        };
        var builder = new AIKit.Storage.Azure.StorageProviderBuilder()
            .WithConnectionString("UseDevelopmentStorage=true")
            .WithContainerName("test-container")
            .WithOptions(options);

        // Act
        var provider = builder.Build();

        // Assert
        provider.ShouldNotBeNull();
    }

    [Fact]
    public void AzureBlobStorageBuilder_Build_MissingConnectionString_ThrowsException()
    {
        // Arrange
        var builder = new AIKit.Storage.Azure.StorageProviderBuilder()
            .WithContainerName("test-container");

        // Act & Assert
        var exception = Should.Throw<InvalidOperationException>(() => builder.Build());
        exception.Message.ShouldBe("ConnectionString must be configured for Azure Blob storage.");
    }

    [Fact]
    public void AzureBlobStorageBuilder_Build_MissingContainerName_ThrowsException()
    {
        // Arrange
        var builder = new AIKit.Storage.Azure.StorageProviderBuilder()
            .WithConnectionString("UseDevelopmentStorage=true");

        // Act & Assert
        var exception = Should.Throw<InvalidOperationException>(() => builder.Build());
        exception.Message.ShouldBe("ContainerName must be configured for Azure Blob storage.");
    }

    [Fact]
    public void LocalStorageBuilder_Build_WithValidBasePath_ReturnsProvider()
    {
        // Arrange
        var basePath = Path.Combine(Path.GetTempPath(), "test-storage");
        var builder = new AIKit.Storage.Local.StorageProviderBuilder()
            .WithBasePath(basePath);

        // Act
        var provider = builder.Build();

        // Assert
        provider.ShouldNotBeNull();
        provider.ShouldBeOfType<AIKit.Storage.Local.LocalVersionedStorageProvider>();
    }

    [Fact]
    public void LocalStorageBuilder_Build_WithOptions_ReturnsProvider()
    {
        // Arrange
        var options = new AIKit.Storage.Local.LocalStorageOptions
        {
            BasePath = Path.Combine(Path.GetTempPath(), "test-storage-options")
        };
        var builder = new AIKit.Storage.Local.StorageProviderBuilder()
            .WithOptions(options);

        // Act
        var provider = builder.Build();

        // Assert
        provider.ShouldNotBeNull();
    }

    [Fact]
    public void LocalStorageBuilder_Build_MissingBasePath_ThrowsException()
    {
        // Arrange
        var builder = new AIKit.Storage.Local.StorageProviderBuilder();

        // Act & Assert
        var exception = Should.Throw<InvalidOperationException>(() => builder.Build());
        exception.Message.ShouldBe("BasePath must be configured for local storage.");
    }
}