using Anthropic;

namespace AIKit.Clients.Claude;

/// <summary>
/// Internal creator for Claude clients with shared configuration logic.
/// </summary>
internal static class ClientCreator
{
    /// <summary>
    /// Creates an AnthropicClient from the provided settings.
    /// </summary>
    /// <param name="apiKey">The API key.</param>
    /// <param name="baseUrl">Optional base URL.</param>
    /// <param name="timeoutSeconds">Timeout in seconds (default: 30).</param>
    /// <param name="maxRetries">Maximum retries.</param>
    /// <returns>The configured AnthropicClient.</returns>
    internal static AnthropicClient CreateAnthropicClient(
        string apiKey,
        string? baseUrl = null,
        int timeoutSeconds = 30,
        int? maxRetries = null)
    {
        var options = new Anthropic.Core.ClientOptions()
        {
            ApiKey = apiKey,
            Timeout = TimeSpan.FromSeconds(timeoutSeconds),
        };

        if (!string.IsNullOrEmpty(baseUrl)) options.BaseUrl = baseUrl;
        if (maxRetries.HasValue) options.MaxRetries = maxRetries.Value;

        return new AnthropicClient(options);
    }
}

// Generated by Copilot