using OpenAI;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Net;

namespace AIKit.Clients.GitHub;

/// <summary>
/// Internal creator for GitHub clients with shared configuration logic.
/// </summary>
internal static class ClientCreator
{
    /// <summary>
    /// Creates an OpenAIClient configured for GitHub Models from the provided settings.
    /// </summary>
    /// <param name="gitHubToken">The GitHub token for authentication.</param>
    /// <param name="organizationId">Optional organization ID.</param>
    /// <param name="projectId">Optional project ID.</param>
    /// <param name="endpoint">The endpoint URL.</param>
    /// <param name="httpClient">Optional pre-configured HttpClient.</param>
    /// <param name="proxy">Optional web proxy.</param>
    /// <param name="timeoutSeconds">Timeout in seconds (default: 30).</param>
    /// <returns>The configured OpenAIClient.</returns>
    internal static OpenAIClient CreateOpenAIClient(
        string gitHubToken,
        string? organizationId = null,
        string? projectId = null,
        string endpoint = Constants.GitHubModelsEndpoint,
        HttpClient? httpClient = null,
        IWebProxy? proxy = null,
        int timeoutSeconds = 30)
    {
        var options = new OpenAIClientOptions();

        if (!string.IsNullOrEmpty(endpoint))
        {
            options.Endpoint = new Uri(endpoint);
        }

        if (!string.IsNullOrWhiteSpace(organizationId))
        {
            options.OrganizationId = organizationId;
        }

        if (!string.IsNullOrEmpty(projectId))
        {
            options.ProjectId = projectId;
        }

        if (httpClient != null)
        {
            options.Transport = new HttpClientPipelineTransport(httpClient);
        }
        else
        {
            if (proxy != null)
            {
                var handler = new HttpClientHandler { Proxy = proxy };
                httpClient = new HttpClient(handler);
            }
            else
            {
                httpClient = new HttpClient();
            }
            httpClient.Timeout = TimeSpan.FromSeconds(timeoutSeconds);
            options.Transport = new HttpClientPipelineTransport(httpClient);
        }

        var credential = new ApiKeyCredential(gitHubToken);
        return new OpenAIClient(credential, options);
    }
}

// Generated by Copilot