using Amazon;
using Amazon.BedrockRuntime;
using Amazon.Runtime;

namespace AIKit.Clients.Bedrock;

/// <summary>
/// Internal creator for Bedrock clients with shared configuration logic.
/// </summary>
internal static class ClientCreator
{
    /// <summary>
    /// Creates an AmazonBedrockRuntimeClient from the provided settings.
    /// </summary>
    /// <param name="awsRegion">The AWS region.</param>
    /// <param name="awsAccessKey">The AWS access key (optional if credentials provided).</param>
    /// <param name="awsSecretKey">The AWS secret key (optional if credentials provided).</param>
    /// <param name="awsCredentials">Pre-configured AWS credentials.</param>
    /// <param name="timeoutSeconds">Timeout in seconds (default: 30).</param>
    /// <param name="maxRetries">Maximum error retries.</param>
    /// <param name="serviceUrl">Custom service URL.</param>
    /// <returns>The configured AmazonBedrockRuntimeClient.</returns>
    internal static AmazonBedrockRuntimeClient CreateBedrockRuntimeClient(
        string awsRegion,
        string? awsAccessKey = null,
        string? awsSecretKey = null,
        AWSCredentials? awsCredentials = null,
        int timeoutSeconds = 30,
        int? maxRetries = null,
        string? serviceUrl = null)
    {
        var regionEndpoint = RegionEndpoint.GetBySystemName(awsRegion);

        AWSCredentials credentials;
        if (awsCredentials != null)
        {
            credentials = awsCredentials;
        }
        else
        {
            credentials = new BasicAWSCredentials(awsAccessKey!, awsSecretKey!);
        }

        var config = new AmazonBedrockRuntimeConfig();
        config.RegionEndpoint = regionEndpoint;
        if (maxRetries.HasValue) config.MaxErrorRetry = maxRetries.Value;
        config.Timeout = TimeSpan.FromSeconds(timeoutSeconds);
        if (!string.IsNullOrEmpty(serviceUrl)) config.ServiceURL = serviceUrl;

        return new AmazonBedrockRuntimeClient(credentials, config);
    }
}

// Generated by Copilot